export const enum RendererToMainEvent {
  INVOKE_RESOURCES_LIMITS = "INVOKE_RESOURCES_LIMITS",
  INVOKE_RESOURCES_USAGE = "INVOKE_RESOURCES_USAGE",
  INVOKE_CHANGE_FRAME_STATUS = "INVOKE_CHANGE_FRAME_STATUS",
}

export const enum MainToRendererEvent {
  SEND_RESOURCES_USAGE = "SEND_RESOURCES_USAGE",
}

export const enum FrameStatus {
  CLOSE = "CLOSE",
  MINIMIZE = "MINIMIZE",
}
